## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: installing clab
  become: true
  shell: bash -c "$(wget -qO - https://get.containerlab.dev)"
  when: validate_certs and (installation_mode == 'online')

- name: Create clab installation directory
  become: true
  file:
    path: "{{ tmp_directory }}/clab_install"
    state: directory
  when:  (not validate_certs) or (installation_mode == 'offline')

- name: Download, configure, and Execute the clabinstaller.sh
  block:
    - name: Download clab script
      ansible.builtin.get_url:
        url: "https://get.containerlab.dev"
        dest: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
        mode: 0755
        validate_certs: false

    - name: "Replace for curl insecure mode1"
      replace:
        path: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
        regexp: 'curl -s'
        replace: 'curl -ks'
        backup: yes

    - name: "Replace for curl insecure mode2"
      replace:
        path: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
        regexp: 'curl -S'
        replace: 'curl -kS'
        backup: yes

    - name: "Replace for wget insecure mode"
      replace:
        path: "{{ tmp_directory }}/clab_install/clabinstaller.sh"
        regexp: 'wget -q'
        replace: 'wget --no-check-certificate -q'
        backup: yes

    - name: Execute the clabinstaller.sh
      become: true
      shell: bash -c "{{ tmp_directory }}/clab_install/clabinstaller.sh"    
  when: (not validate_certs) and (installation_mode == 'online')
  become: true

- name: Copy and Execute the clabinstaller
  block:
    - name: Copy clab binary to tmp_directory
      become: true
      ansible.builtin.copy:
        src: "{{ installer_lib }}/{{ item }}"
        dest: "{{ tmp_directory }}/clab_install/{{ item }}"
        mode: "0755"
        owner: "root"
        group: "root"
        remote_src: true
      with_items:
        - clab.deb

    - name: Installing clab
      become: true
      shell: "dpkg -i {{ tmp_directory }}/clab_install/{{ item }}"
      with_items:
        - clab.deb      
  when: (installation_mode == 'offline')
  become: true

- name: Remove the clabinstaller.sh
  become: true
  file:
    path: "{{ tmp_directory }}/clab_install"
    state: absent
  when: (not validate_certs) or (installation_mode == 'offline')
